# Generated by Django 3.2.7 on 2022-05-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_rename_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]